apiVersion: gameplane.local/v1alpha1
kind: GameServer
metadata:
  name: arma-reforger-01
  namespace: gameplane-games
spec:
  templateRef:
    name: arma-reforger

  config:
    SERVER_NAME: "Gameplane Arma Reforger Server"
    SERVER_PASSWORD: ""
    ADMIN_PASSWORD: "secret-admin-pass"
    MAX_PLAYERS: 64

  networking:
    expose: NodePort
    portOverrides:
      - name: game
        nodePort: 32001
      - name: query
        nodePort: 31777

  storage:
    size: 30Gi

  resources:
    requests: { cpu: 2, memory: 8Gi }
    limits:   { cpu: 6, memory: 16Gi }
