apiVersion: gameplane.local/v1alpha1
kind: GameServer
metadata:
  name: the-isle-01
  namespace: gameplane-games
spec:
  templateRef:
    name: the-isle

  config:
    SERVER_NAME: "Gameplane The Isle Server"
    SERVER_PASSWORD: ""
    RCON_PASSWORD: "secret-rcon-password"
    MAX_PLAYERS: 50

  networking:
    expose: NodePort
    portOverrides:
      - name: game
        nodePort: 30777
      - name: query
        nodePort: 30778

  storage:
    size: 25Gi

  resources:
    requests: { cpu: 2, memory: 4Gi }
    limits:   { cpu: 4, memory: 8Gi }
